name: Run Downloader

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Comma separated urls to download"
        required: true

permissions:
  contents: read

jobs:
  downloader:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: FedericoCarboni/setup-ffmpeg@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Downloader
        run: |
          python main.py "${{ inputs.urls }}"

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_number }}
          path: output
