name: Run Downloader

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Comma separated urls to download"
        required: true

permissions:
  contents: read

jobs:
  downloader:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Run downloader
        run: |
          python -m pip install -r requirements.txt
          pip freeze
          python main.py "${{ inputs.urls }}"

      - name: Save output
        uses: actions/cache/save@v4
        with:
          path: ./output
          key: output-${{ github.run_number }}
